version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - n 20
      - npm ci --production=false
      - npm run test
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: "dist"