version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - n 20
      - npm ci --production=false
      - npm run test
      - npm run build
      - aws s3 rm --recursive s3://${DEPLOY_BUCKET_NAME}
      - aws s3 sync dist s3://${DEPLOY_BUCKET_NAME} --region=ap-northeast-1